/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_archsoft_TextCase */

#ifndef _Included_com_archsoft_TextCase
#define _Included_com_archsoft_TextCase
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_archsoft_TextCase
 * Method:    upcase
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_archsoft_TextCase_upcase
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_archsoft_TextCase
 * Method:    lowcase
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_archsoft_TextCase_lowcase
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
