spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    hikari:
      connectionTimeout: 10000
      maximumPoolSize: 5
    url: jdbc:postgresql://postgres:5432/postgres
    username: postgres
    password: socrates