INSERT INTO public.tb02_person (person_id, person_age, person_name) VALUES (102, 50, 'Joao da Silva');
INSERT INTO public.tb02_person (person_id, person_age, person_name) VALUES (852, 33, 'Francisco Vieira');
INSERT INTO public.tb02_person (person_id, person_age, person_name) VALUES (853, 55, 'Luciano de Souza');
INSERT INTO public.tb02_person (person_id, person_age, person_name) VALUES (854, 45, 'Amanda Silva');
INSERT INTO public.tb02_person (person_id, person_age, person_name) VALUES (855, 76, 'Waldisney Clemente');
INSERT INTO public.tb02_person (person_id, person_age, person_name) VALUES (856, 23, 'Jose Lima e Silva');
INSERT INTO public.tb02_person (person_id, person_age, person_name) VALUES (857, 54, 'Edson de Souza');
INSERT INTO public.tb02_person (person_id, person_age, person_name) VALUES (858, 22, 'EDUARDO RIBEIRO');
INSERT INTO public.tb02_person (person_id, person_age, person_name) VALUES (859, 22, 'asdsdasd');
INSERT INTO public.tb02_person (person_id, person_age, person_name) VALUES (860, 22, 'wqeqwe');
INSERT INTO public.tb02_person (person_id, person_age, person_name) VALUES (861, 99, 'Eduardo');
INSERT INTO public.tb02_person (person_id, person_age, person_name) VALUES (902, 33, 'Fulano de Tal');