apiVersion: v1
kind: Service
metadata:
  name: angular06-inventory-svc
  labels:
    app: angular06-inventory
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30001
    protocol: TCP
  selector:
    app: angular06-inventory

# Access the app from
# - From inside the cluster using DNS name hello-svc on port 8080
# - From outside the cluster by hitting any of the cluster nodes on port 30001    