server:
  port: 8082
  servlet:
    context-path: /product

spring:
  application:
    name: product
  data:
    mongodb:
      host: localhost
      port: 27017
      database: product

security:
  jwt:
    token:
      secret-key: asoiuiey8723389uiajnmc*&%^^#$^&*092183797hj
      expire-length: 3600000
  auth:
    url: http://localhost:8080/api/auth

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/registry/eureka


kafka:
  bootstrap:
    host: 127.0.0.1
    port: 9092
  topic:
    product: product
    addProductToOrder: addProductToOrder

logging:
  level:
    root: INFO