version: "3.7"
services:
  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: "socrates"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose: 
      - 5432
    ports:
      - "5432:5432"
    network_mode: bridge
    restart: unless-stopped  

  backend:
    build:
      context: ./spring-10
      dockerfile: Dockerfile
    container_name: spring-10
    restart: unless-stopped
    expose:
      - 8080
    ports:
      - "8080:8080"
    network_mode: bridge  
    depends_on: 
      - db
    links:
      - db

  frontend:
    build:      
      context: ./angular31-spring10
      dockerfile: Dockerfile
    # image: nginx:alpine
    container_name: angular31-spring10
    restart: unless-stopped
    # working_dir: /var/www/
    volumes:
      - ./angular31-spring10/dist/angular31-spring10:/usr/share/nginx/html
    expose:
      - 80
    ports:
      - "80:80"  
    # depends_on: 
      # - backend

volumes:
  postgres-data:

# networks: 
  # angular31-spring10:
      # driver: bridge      

