server:
  port: 8082

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: authentication

security:
  jwt:
    token:
      secret-key: asoiuiey8723389uiajnmc*&%^^#$^&*092183797hj
      expire-length: 360000