spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    hikari:
      connectionTimeout: 10000
      maximumPoolSize: 5
    url: jdbc:postgresql://localhost:31070/postgres
    #url: jdbc:postgresql://postgres-service.default:5432/postgres
    username: postgresadmin
    password: admin123
