#application: theairhorner
#version: 1
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "10s"

handlers:
- url: /manifest.json
  mime_type: application/json
  static_files: dist/manifest.json
  upload: dist/manifest.json
  secure: always
  http_headers:
    Access-Control-Allow-Origin: "*"

- url: /
  mime_type: text/html
  static_files: dist/index.html
  secure: always
  upload: dist/index.html

- url: /(.+)
  static_files: dist/\1
  upload: dist/(.+)
  secure: always
  http_headers:
    Access-Control-Allow-Origin: "*"

skip_files:
- ^.tmp/.*
- ^app/.*
- ^jsqrcode/.*
- ^node_modules/.*
