server:
  port: 8761
  servlet:
    context-path: /registry

spring:
    application:
      name: Registry

eureka:
  client:
    register-with-eureka: false
#    fetch-registry: false
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:${server.port}/eureka
