apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deploy
spec:
  replicas: 10
  selector:
    matchLabels:
      app: hello-world
  minReadySeconds: 10   # Wait 10 secs between each Pod being update
  strategy:
    type: RollingUpdate # Type of update strategy
    rollingUpdate:
      maxUnavailable: 1 # Never have more than 1 Pod below desired state (never < 9)
      maxSurge: 1       # Never have more than 1 Pod above desired state (never > 11) : Net result (11-9 = 2 Pods at time)
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-pod
        image: nigelpoulton/k8sbook:latest
        # image: nigelpoulton/k8sbook:edge
        ports:
        - containerPort: 8080