apiVersion: v1
kind: Service
metadata:
  name: hello-svc
  labels:
    app: hello-world
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30001
    protocol: TCP
  selector:
    app: hello-world

# Access the app from
# - From inside the cluster using DNS name hello-svc on port 8080
# - From outside the cluster by hitting any of the cluster nodes on port 30001    